DotNetCore/Models/Category.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DotNetCore.Models
{
    [Table("Category")]
    public class Category
    {
        [Key]
        public int CategoryId { get; set; }
        public string Name { get; set; }
    }
}

DotNetCore/Controllers/CategoryController.cs
using DotNetCore.Data;
using DotNetCore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DotNetCore.Controllers
{
    public class CategoryController : Controller
    {
        MyDbContext context = new MyDbContext();
        public IActionResult Index()
        {
            // There are 2 ways tomtransfer data from Controller to View 
            // 1. ViewBag, ViewData, TempData, Session
            // 2. Model

            // Get CategoryList from the Database
            var CategoryList = context.Category.ToList();

            // Ways to assign data in Category
            // 1. Declare obj then assign.
            //Category obj1 = new Category() { CategoryId=1, Name= "Fruits" };
            //Category obj2 = new Category() { CategoryId=2, Name= "Vegetables" };
            //Category obj3 = new Category() { CategoryId=3, Name= "Beverages" };
            //CategoryList.Add(obj1);
            //CategoryList.Add(obj2);
            //CategoryList.Add(obj3);

            // 2. Declare and assign at once.
            CategoryList.Add(new Category() {CategoryId=1, Name="Fruits"});
            CategoryList.Add(new Category() {CategoryId=2, Name="Vegetables"});
            CategoryList.Add(new Category() {CategoryId=3, Name="Beverages"});
            ViewBag.CategoryList = CategoryList;    
            return View();
        }
    }
}

DotNetCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace DotNetCore.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DotNetCore/Controllers/ManufacturerController.cs
using Microsoft.AspNetCore.Mvc;

namespace DotNetCore.Controllers
{
    public class ManufacturerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DotNetCore/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace DotNetCore.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

DotNetCore/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCore.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

DotNetCore/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCore.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

DotNetCore/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCore.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

DotNetCore/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DotNetCore/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DotNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">DotNetCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DotNetCore - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

DotNetCore/Views/Category/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/_Layout.cshtml";
}

<h1>Category List</h1>

<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.CategoryList)
        {
            <tr>
                <td>@item.CategoryId</td>
                <td>@item.Name</td>
            </tr>
        }
       
    </tbody>

</table>

DotNetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/_Layout.cshtml";
}

<h1>This is my Home page</h1>

DotNetCore/Views/Manufacturer/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/_Layout.cshtml";
}

<h1>This is a Manufacturer Page.</h1>

DotNetCore/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/_Layout.cshtml";
}

<h1>This is my Product page</h1>

DotNetCore/Views/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/twitter-bootstrap/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Specy</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="nav-link" asp-controller="Category" asp-action="Index">Category</a>
                    <a class="nav-link" asp-controller="Product" asp-action="Index">Product</a>
                    <a class="nav-link" asp-controller="Manufacturer" asp-action="Index">Manufacturer</a>
                </div>
            </div>
        </div>
    </nav>

    <div>
        @RenderBody()
    </div>
</body>
</html>